const aboutData = [
    {
        textNode: "FOOD BLOG is a unique lifestyle network, website and magazine that connects viewers to the power and joy of food. The network strives to be viewers' best friend in food and is committed to leading by teaching, inspiring, empowering and entertaining through its talent and expertise. Food Network is distributed to nearly 100 million U.S. households and draws over 46 million unique web users monthly. Since launching in 2009, Food Network Magazine's rate base has grown 13 times and is the No. 2 best-selling monthly magazine on the newsstand, with 13.5 million readers. Food Network is owned by Discovery, Inc., a global leader in real life entertainment whose portfolio also includes Discovery Channel, HGTV, TLC, Investigation Discovery, and OWN: Oprah Winfrey Network.",
        galleryImg: [
            '../img/About/gallery/img_1.jpg', '../img/About/gallery/img_2.jpg', '../img/About/gallery/img_3.jpg',
            '../img/About/gallery/img_4.jpg', '../img/About/gallery/img_5.jpg', '../img/About/gallery/img_7.jpg'
        ],
        textContribute: "We are a member of the AT Media family of sites, along with Apartment Therapy. We publish 20 short articles daily that inform and inspire every aspect of home cooking, from recipes to cooking lessons to product reviews to kitchen design and renovation advice. This is a site for people who like to get their hands dirty while they cook. It is for those who care about the quality of their food, and how it affects the health of themselves and the planet. It is for cooks who care about design and want to create a beautiful kitchen. It's a place to dive in deep, and embrace the joy of one of our basic needs: Food, cooked at home, nourishing ourselves and our households. Salt & Papper was founded in 2005 by Maxwell Ryan and Sara Kate Gillingham, also the founders of The Kitchn's companion site, Apartment Therapy. Today Food Blog is brought to you by a diverse team of editors, writers, recipe developers, and photographers from across the country. If you want to get an overview of everything we have in our archives, check out our Category Index it's helpful for browsing. The Kitchn's Category Index How Can I Contribute? The Kitchn is written by a small, steady team of freelance writers and we do not at this time accept unsolicited freelance submissions. However, we do hire from time to time, so keep an eye on our Job Listings for future postings. We do not accept unsolicited guest posts. If, however, you are a reader or a blogger who would like to share a kitchen project or recipe link from your own site with our audience, we would love to hear from you! We also are always accepting questions from our readers, which are published in our Good Questions column. Click the link below to contact us with any of these!"
    }
]